# Generated by Django 5.0.7 on 2024-07-11 20:19

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Moment when user information is initially obtained', verbose_name='creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Moment when user information is updated', verbose_name='update timestamp')),
            ],
            options={
                'verbose_name': 'API Client',
                'verbose_name_plural': 'API Clients',
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Moment when user information is initially obtained', verbose_name='creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Moment when user information is updated', verbose_name='update timestamp')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='rnecco_app.apiclient')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_body', models.JSONField(blank=True, default=dict, help_text='Request')),
                ('response_body', models.JSONField(blank=True, default=dict, help_text='Response')),
                ('status_code', models.IntegerField(help_text='Status code')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Created', verbose_name='creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Moment when user information is updated', verbose_name='update timestamp')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_logs', to='rnecco_app.apikey')),
            ],
            options={
                'verbose_name': 'Request Log',
                'verbose_name_plural': 'Request Logs',
            },
        ),
        migrations.CreateModel(
            name='IdentityInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification_number', models.CharField(max_length=20, unique=True)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('issue_place', models.CharField(max_length=100)),
                ('name', models.TextField()),
                ('status', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Initial moment when user information is initially obtained', verbose_name='creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Moment when user information is updated', verbose_name='update timestamp')),
                ('api_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identity_information', to='rnecco_app.apikey')),
            ],
            options={
                'verbose_name': 'Identity Information',
                'verbose_name_plural': 'Identity Information',
                'unique_together': {('identification_number', 'issue_date')},
            },
        ),
    ]
